<div class="form-floating mt-5 ms-5">
<h3 style="color: white;" class="text-center mb-3">11 - Vectores (tradicionales)</h3>
    <textarea class="form-control w-50 mx-auto" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 400px">
            DESARROLLO
            echo "RESULTADO: ";
            echo "
            ";
            $diasSemana[] = "Lunes";
            $diasSemana[] = "Martes";
            $diasSemana[] = "Miercoles";
            $diasSemana[] = "Jueves";
            $diasSemana[] = "Viernes";
            $diasSemana[] = "Sabado";
            $diasSemana[] = "Domingo";

            echo "El primer dia de la semana es $diasSemana[0] y el ultimo dia de la semana es $diasSemana[6]";


        <?php
            echo "RESULTADO: ";
            echo "
            ";
            $diasSemana[] = "Lunes";
            $diasSemana[] = "Martes";
            $diasSemana[] = "Miercoles";
            $diasSemana[] = "Jueves";
            $diasSemana[] = "Viernes";
            $diasSemana[] = "Sabado";
            $diasSemana[] = "Domingo";

            echo "El primer dia de la semana es $diasSemana[0] y el ultimo dia de la semana es $diasSemana[6]";

        ?>
    </textarea>
</div>